[project]
name = "gfv2-params"
version = "0.1.0"
description = "Geospatial analysis project with marimo workflows"
authors = [{name = "Your Name", email = "you@example.com"}]
dependencies = [
    "gdptools=0.2.21",
    "marimo[recommended]",
    "plotly",
    "pandas",
    "numpy",
    "hvplot",
    "geoviews",
    "datashader",
    "dask",
    "intake",
    "intake-xarray",
    "intake-parquet",
    "s3fs",
    "pooch",
    "matplotlib",
    "py7zr",
    "simple_parsing",
    "ipykernel",
    "dask",
    "distributed",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pre-commit",
    "ruff",
]

[tool.isort]
profile = "black"   # Or "ruff", "black", "django", etc. (recommended for compatibility)
line_length = 120    # Match your code style/black config

[tool.ruff]
extend-ignore = ["F722"]

[tool.uv]
# uv-specific settings (optional)
