"""Cloud-Optimized GeoTIFF conversion for the visualization/processing mosaic.

The continental elevation mosaic feeds two consumers: interactive QGIS over
Lustre (needs overviews + internal tiling for fast continental pan/zoom) and
downstream geospatial processing (zonal stats / resampling via
gdptools/exactextract/rioxarray — needs fast windowed block reads). Both want
the same thing: tiled, overviewed, compressed rasters. :func:`to_cog` produces
exactly that.

WBT-SAFETY BOUNDARY — READ BEFORE REUSING THIS HELPER
-----------------------------------------------------
This helper emits ``ZSTD`` + ``PREDICTOR`` GeoTIFFs. WhiteboxTools' built-in
TIFF reader silently produces garbage on horizontal-/floating-point-differencing
predictor input (see ``compute_dem_derivatives._fix_dem_nodata`` and CLAUDE.md).
Use :func:`to_cog` ONLY for rasters consumed exclusively by GDAL/rasterio/QGIS:

  * ``NEDSnapshot_merged_fixed_*`` (elevation), ``*_slope_*``, ``*_aspect_*``
    — the elevation-mosaic VRT sources.

NEVER route a WBT-fed raster through here. Those (the ``Hydrodem`` fixed/filled
DEMs in ``compute_dem_derivatives`` and the depstor routing FDR) must stay
LZW-without-predictor and are deliberately left on their existing write paths.
"""

from __future__ import annotations

from pathlib import Path

from osgeo import gdal

# Shared COG creation profile. BLOCKSIZE=512 matches the per-VPU base tiles and
# the depstor/border conventions; ZSTD+predictor beats LZW on continuous float
# DEMs; overviews are generated by the COG driver (OVERVIEWS=AUTO is implicit
# when source has none). NUM_THREADS speeds the CONUS-scale per-VPU tiles.
_COG_BLOCKSIZE = "512"
_COG_COMPRESS = "ZSTD"
_COG_LEVEL = "15"


def to_cog(
    src: str | Path,
    dst: str | Path,
    *,
    overview_resampling: str,
    predictor: int,
) -> Path:
    """Rewrite ``src`` as a Cloud-Optimized GeoTIFF at ``dst``.

    Parameters
    ----------
    src, dst:
        Input GeoTIFF and output COG paths.
    overview_resampling:
        GDAL resampling for the internal overview pyramid. Use ``"BILINEAR"``
        (or ``"CUBIC"``) for continuous surfaces (elevation, slope); use
        ``"NEAREST"`` for circular/categorical fields where averaging is wrong
        (aspect's 0/360 wrap, FDR D8 codes).
    predictor:
        TIFF predictor. ``3`` (floating-point) for Float32/Float64, ``2``
        (horizontal) for integer data. Never use a predictor for a WBT-fed
        raster — see the module docstring.

    Returns the ``dst`` path.
    """
    src = Path(src)
    dst = Path(dst)
    creation_options = [
        f"BLOCKSIZE={_COG_BLOCKSIZE}",
        f"COMPRESS={_COG_COMPRESS}",
        f"LEVEL={_COG_LEVEL}",
        f"PREDICTOR={predictor}",
        f"OVERVIEW_RESAMPLING={overview_resampling}",
        "BIGTIFF=YES",
        "NUM_THREADS=ALL_CPUS",
    ]
    out = gdal.Translate(
        str(dst),
        str(src),
        options=gdal.TranslateOptions(format="COG", creationOptions=creation_options),
    )
    if out is None:
        raise RuntimeError(f"gdal.Translate to COG failed: {src} -> {dst} — {gdal.GetLastErrorMsg()}")
    out.FlushCache()
    del out
    return dst
