base_source_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/source_data/NHDPlus_Merged_Rasters
target_source_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/targets
output_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/nhm_params
source_type: slope
categorical: False
