base_source_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/source_data
target_source_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/targets
weight_dir: "/caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/weights"
output_dir: /caldera/hovenweep/projects/usgs/water/impd/nhgf/gfv2_param/nhm_params
source_type: ssflux
merged_file: nhm_ssflux_params.csv
categorical: False
