source_type: slope
source_raster: "{data_root}/work/nhd_merged/slope.vrt"
batch_dir: "{data_root}/{fabric}/batches"
target_layer: nhru
id_feature: nat_hru_id
output_dir: "{data_root}/{fabric}/params"
merged_file: nhm_slope_params.csv
categorical: false
