source_type: soils
source_raster: "{data_root}/input/soils_litho/TEXT_PRMS.tif"
batch_dir: "{data_root}/{fabric}/batches"
target_layer: nhru
id_feature: nat_hru_id
output_dir: "{data_root}/{fabric}/params"
merged_file: nhm_soils_params.csv
categorical: true
