"""Scaffold the data_root directory layout for gfv2-params.

Creates the expected directory tree under data_root (from base_config.yml or
--data_root) and writes a README.txt into each top-level directory explaining
its purpose and what files belong there.

Run this once before populating a new data root:
    python scripts/init_data_root.py
or for a custom root:
    python scripts/init_data_root.py --data_root /path/to/new_root --fabric myfabric

To register a brand-new fabric, append a profile stub to base_config.yml and
scaffold its directories in one step:
    pixi run init-data-root --add-fabric oregon
The stub is a COMPLETE, ACTIVE profile (the tjc/flaming_gorge shape): every
depstor key is wired to its shared CONUS input. Only four values are
fabric-specific and carry a TODO: expected_max_hru_id, id_feature, the
hru_gpkg filename, and vpu. The plain-language walkthrough is
docs/adding-a-fabric.md; validate the filled profile against the gpkg with
scripts/check_fabric_profile.py before submitting anything.
"""

import argparse
import re
import textwrap
from pathlib import Path

from gfv2_params.config import _DEFAULT_BASE_CONFIG, SHARED_DEPSTOR_INPUT_KEYS, load_base_config
from gfv2_params.log import configure_logging

# ---------------------------------------------------------------------------
# Directory skeleton
# Each entry is (relative_path, readme_text).  Paths ending in / are dirs;
# the readme_text is written as README.txt inside that directory.
# ---------------------------------------------------------------------------
_TREE = [
    # ---- inputs ------------------------------------------------------------
    (
        "input",
        """\
        INPUT — externally sourced data
        ================================
        All files here are provided externally and are NOT generated by this
        pipeline.  Do not delete them; they cannot be reproduced automatically.

        Subdirectory layout:
          fabric/           Per-VPU watershed fabric GeoPackages
                            (NHM_<VPU>_draft.gpkg, one per VPU)
          soils_litho/      Soils and lithology rasters/shapefiles
                            (TEXT_PRMS.tif, AWC.tif,
                             Lithology_exp_Konly_Project.*)
          lulc_veg/         Land use / land cover and vegetation rasters
                            (RootDepth.tif, CNPY.tif, Imperv.tif)
          lulc_veg/nhm_v11/ NHM v1.1 pre-derived LULC rasters
                            (LULC.tif, keep.tif, CNPY.tif)
                            (downloadable via download/nhm_v11_lulc.py)
          lulc/nlcd_annual_imperv/
                            Annual NLCD fractional imperviousness rasters
                            (downloadable via download/mrlc_impervious.py)
          lulc/nalcms_2020/ North America land cover 2020 at 30 m
                            (NA_NALCMS_landcover_2020v2_30m.tif)
                            (downloadable via download/nalcms_lulc.py)
          nhm_default/      NHM default parameter files (input to final merge)
          nhd_downloads/    Raw NHDPlus zip archives
                            (downloadable via download/rpu_rasters.py)
          nhd/              Shared NHDPlusV2 layers every depstor fabric reads:
                            nhd_waterbodies.gpkg, burn_add_waterbodies.parquet,
                            sink_points.parquet (gfv2_params.download.nhd_waterbodies
                            and .nhd_burn_components). Stream segments are NOT
                            staged here: they come from the fabric's own gpkg
                            (profile key segments_gpkg), and the FDR from the
                            shared shared/conus/vrt/fdr.vrt.
          wbd/              wbd_huc12.parquet (gfv2_params.download.wbd_huc12)
          3dep/             dem_1m_tile_inventory.parquet -- every published 3DEP
                            1 m tile with its real extent
          wesm/             wesm_project_attrs.parquet -- WESM project attributes
                            (both staged by slurm_batch/stage_dem_1m_inventory.batch)
          ecoregions/       us_eco_l3.gpkg (gfv2_params.download.epa_ecoregions)
          twi/<rpu>/        Per-RPU topographic wetness index rasters
                            (twi.tif + .tfw/.aux.xml/.ovr/.xml sidecars).
                            Provenance: USGS ScienceBase 5f5154ba82ce4c3d12386a02
                            (https://www.sciencebase.gov/catalog/item/5f5154ba82ce4c3d12386a02 —
                            non-public link). Stage with scripts/stage_twi.sh,
                            which reads from a shared cluster mirror by default.
        """,
    ),
    ("input/fabric", None),
    ("input/soils_litho", None),
    ("input/lulc_veg", None),
    ("input/lulc_veg/nhm_v11", None),
    ("input/lulc/nlcd_annual_imperv", None),
    ("input/lulc/nalcms_2020", None),
    ("input/nhm_default", None),
    ("input/nhd_downloads", None),
    ("input/copernicus_dem", None),
    ("input/copernicus_dem/raw", None),
    ("input/nhd", None),
    ("input/wbd", None),
    ("input/3dep", None),
    ("input/wesm", None),
    ("input/ecoregions", None),
    ("input/twi", None),
    # ---- shared (fabric-independent intermediates) -----------------------
    (
        "shared",
        """\
        SHARED — fabric-independent pipeline intermediates
        ===================================================
        All files here are generated by this pipeline and are reused across
        every fabric. Safe to delete and rebuild (use
        scripts/build_shared_rasters.py over configs/shared_rasters/shared_rasters.yml).
        Do NOT hand-edit files here.

        Subdirectory layout:
          source/             Unzipped per-RPU NHDPlus rasters
                              (reproducible from input/nhd_downloads/ —
                               safe to delete if disk space is tight)
          per_vpu/<VPU>/      Per-VPU merged GeoTIFFs produced by the
                              shared_rasters pipeline (NEDSnapshot_merged_*.tif,
                              Hydrodem_merged_*.tif, Fdr_merged_*.tif,
                              Fac_merged_*.tif, *_slope_*.tif, *_aspect_*.tif,
                              land_mask_<vpu>.tif)
          conus/vrt/          CONUS-wide GDAL virtual rasters built by
                              build_vrt (elevation.vrt, slope.vrt,
                              aspect.vrt, fdr.vrt, twi.vrt)
          conus/derived/      Derived rasters written during parameter
                              computation (e.g. soil_moist_max.tif,
                              radtrn_<source>.tif, cnpy_resampled_<source>.tif)
          conus/borders/      Copernicus border-DEM fill (Canada/Mexico)
          conus/weights/      Polygon-to-polygon weight tables built by
                              build_weights.py (lith_weights_<fabric>.csv)
        """,
    ),
    ("shared/source", None),
    ("shared/per_vpu", None),
    ("shared/conus", None),
    ("shared/conus/vrt", None),
    ("shared/conus/derived", None),
    ("shared/conus/borders", None),
    ("shared/conus/weights", None),
]


def _fabric_tree(fabric: str) -> list:
    """Return per-fabric directory entries."""
    return [
        (
            fabric,
            f"""\
            {fabric.upper()} — fabric-scoped outputs
            {"=" * (len(fabric) + 28)}
            All outputs scoped to the '{fabric}' watershed fabric.

            Subdirectory layout:
              fabric/     The fabric GeoPackage named by the profile's hru_gpkg
                          (a single pre-merged gpkg with nhru + nsegment layers,
                          or {fabric}_nhru_merged.gpkg from
                          notebooks/merge_vpu_targets.py for a per-VPU fabric)
              shared/     {fabric}_fdr.vrt -- the fabric-bounds FDR clip written
                          by scripts/clip_shared_to_fabric.py (template_raster
                          and fdr_raster)
              batches/    Spatially-partitioned batch GeoPackages produced by
                          prepare_fabric.py (used by zonal stats scripts)
              depstor_rasters/
                          Per-fabric depression-storage intermediate rasters
                          produced by build_depstor_rasters.py
                          (imperv_binary.tif, connected_wbody.tif,
                           endorheic_wbody.tif, wbody_binary.tif,
                           wbody_regions.tif, dprst_binary.tif,
                           onstream_binary.tif, drains_to_dprst.tif)
              params/     Per-VPU and merged parameter CSVs produced by
                          create_zonal_params.py, create_soils_params.py,
                          create_ssflux_params.py, merge_params.py, and
                          merge_and_fill_params.py
              params/merged/
                          CONUS-wide merged parameter CSVs, including KNN-filled
                          ssflux parameters
            """,
        ),
        (f"{fabric}/fabric", None),
        (f"{fabric}/shared", None),
        (f"{fabric}/batches", None),
        (f"{fabric}/depstor_rasters", None),
        (f"{fabric}/params", None),
        (f"{fabric}/params/merged", None),
    ]


def init_data_root(data_root: Path, fabric: str, logger) -> None:
    tree = _TREE + _fabric_tree(fabric)

    created = []
    skipped = []

    for rel_path, readme in tree:
        d = data_root / rel_path
        if d.exists():
            skipped.append(d)
        else:
            d.mkdir(parents=True, exist_ok=True)
            created.append(d)
            logger.info("Created: %s", d)

        if readme is not None:
            readme_path = d / "README.txt"
            if not readme_path.exists():
                readme_path.write_text(textwrap.dedent(readme))

    logger.info(
        "init_data_root complete: %d created, %d already existed",
        len(created),
        len(skipped),
    )

    if skipped:
        logger.debug("Pre-existing directories (unchanged):")
        for d in skipped:
            logger.debug("  %s", d)


def _shapefile_companions(shp_path: Path) -> list[Path]:
    """Return the required ESRI sidecar paths for a shapefile.

    Shapefiles cannot be opened without `.shx` (index) and `.dbf` (attribute
    table); `.prj` (projection) is required for any CRS-aware read. All three
    must be staged alongside the `.shp` or pyogrio/fiona reads fail with a
    confusing error.

    The sidecar extensions mirror the case of the input `.shp` extension so
    the existence check works on case-sensitive filesystems regardless of
    whether the shapefile was staged lowercase (`.shp`) or uppercase (`.SHP`).
    """
    stem = shp_path.with_suffix("")
    # Mirror the case of the input extension. `.suffix` returns the original
    # case (e.g. ".SHP" stays ".SHP"); the sidecars match that case.
    upper = shp_path.suffix.isupper()
    exts = (".SHX", ".DBF", ".PRJ") if upper else (".shx", ".dbf", ".prj")
    return [stem.with_suffix(ext) for ext in exts]


# Staged inputs with no profile key (cannot be auto-downloaded), plus the two
# shared products every depstor fabric reads by convention rather than via a
# profile key: fdr.vrt is clip_shared_to_fabric's default source, and the
# hydrodem percentile table is what carea_map's percentile mode looks up.
_FIXED_REQUIRED_PATHS = (
    "input/soils_litho/TEXT_PRMS.tif",
    "input/soils_litho/AWC.tif",
    "input/soils_litho/Lithology_exp_Konly_Project.shp",
    "input/lulc_veg/RootDepth.tif",
    # Sentinel for the per-RPU TWI staging step. Run scripts/stage_twi.sh
    # if missing.
    "input/twi/01a/twi.tif",
    "shared/conus/vrt/fdr.vrt",
    "shared/conus/twi_reference_percentiles.hydrodem.csv",
)

# Shared depstor inputs, read from the ACTIVE PROFILE's own values so the check
# can never name a file no profile reads (the retired
# input/depstor/<fabric>_segments_wbodies.gpkg sentinel did exactly that). A key
# a profile does not declare is a documented, legitimate omission (tjc has no
# burn_add_waterbody_table) and is not checked. The key list is shared with
# scripts/check_fabric_profile.py via config.py.
_SHARED_INPUT_PROFILE_KEYS = SHARED_DEPSTOR_INPUT_KEYS


def validate_inputs(data_root: Path, config: dict, logger) -> None:
    """Warn about missing staged inputs that cannot be auto-downloaded.

    `config` is the resolved active profile (load_base_config), so the shared
    depstor inputs are checked at the exact paths the pipeline will open.

    For required `.shp` paths, also validates the `.shx` / `.dbf` / `.prj`
    sidecars — each is reported separately so the user knows exactly what
    to stage.
    """
    required = [data_root / rel for rel in _FIXED_REQUIRED_PATHS]
    required += [Path(config[k]) for k in _SHARED_INPUT_PROFILE_KEYS if k in config]
    # Expand each .shp into the .shp itself + its 3 required sidecars so
    # the user sees exactly which files are missing (not just "the shapefile").
    to_check: list[Path] = []
    for p in required:
        to_check.append(p)
        if p.suffix.lower() == ".shp":
            to_check.extend(_shapefile_companions(p))

    missing = [p for p in to_check if not p.exists()]
    if missing:
        logger.warning(
            "%d required input file(s) are not yet staged:", len(missing)
        )
        for p in missing:
            logger.warning("  MISSING: %s", p)
        logger.warning(
            "Stage these files manually before running the pipeline."
        )
    else:
        logger.info("All required staged inputs are present.")


def _fabric_profile_stub(fabric: str) -> str:
    """Return a YAML profile stub for a new fabric (2-space indented).

    A COMPLETE, ACTIVE profile in the tjc/flaming_gorge shape (a single
    pre-merged gpkg holding nhru + nsegment): every depstor key is wired to its
    real shared CONUS input, not commented out. The old stub commented the
    depstor block out and pointed it at retired paths, so the first outside
    user had to reconstruct it by hand from another profile. Only the four
    fabric-specific values carry a TODO: expected_max_hru_id, id_feature, the
    hru_gpkg filename, and vpu. The two classifier floors stay opt-in.

    tests/test_add_fabric.py pins this against docs/ARCHITECTURE.md's
    required-keys table, so a key added here must be documented there.
    """
    return (
        f"\n"
        f"  {fabric}:\n"
        f"    # See docs/adding-a-fabric.md. Fill the four TODO values, then run\n"
        f"    #   pixi run --as-is python scripts/check_fabric_profile.py --fabric {fabric}\n"
        f"    # TODO: highest value of the id column (must equal the HRU count: ids run 1..N)\n"
        f"    expected_max_hru_id: 0\n"
        f"    batch_size: 10000\n"
        f"    # TODO: the HRU id column in your gpkg. Must be unique and contiguous 1..N;\n"
        f"    # a national id with gaps makes gap-fill invent thousands of phantom HRUs.\n"
        f"    id_feature: nat_hru_id\n"
        f"    # TODO: your gpkg's filename. Put the file under {{data_root}}/{fabric}/fabric/\n"
        f"    # (NOT input/fabric/). One file holds the nhru and nsegment layers.\n"
        f'    hru_gpkg: "{{data_root}}/{{fabric}}/fabric/{fabric}.gpkg"\n'
        f"    hru_layer: nhru\n"
        f'    # TODO: the VPU this fabric lies in, as a string ("12", "14", "17").\n'
        f"    # Delete this line only if the fabric spans several VPUs AND the nhru\n"
        f"    # layer carries a per-HRU `vpu` column (the gfv2 pattern).\n"
        f'    vpu: "00"\n'
        f"    # --- depstor inputs (active: every fabric runs depstor) --------------\n"
        f"    # Fabric-bounds clip of the CONUS fdr.vrt; serves as BOTH template and\n"
        f"    # FDR. Stage it BEFORE the first depstor run:\n"
        f"    #   pixi run --as-is python scripts/clip_shared_to_fabric.py --fabric {fabric}\n"
        f'    template_raster: "{{data_root}}/{{fabric}}/shared/{{fabric}}_fdr.vrt"\n'
        f'    fdr_raster: "{{data_root}}/{{fabric}}/shared/{{fabric}}_fdr.vrt"\n'
        f"    # Open-source, CONUS-complete TWI; carea_map runs in percentile mode\n"
        f"    # against it. Never the legacy twi.vrt (VPU-01-only absolute thresholds).\n"
        f'    twi_raster: "{{data_root}}/shared/conus/vrt/twi_hydrodem.vrt"\n'
        f"    # Stream segments = the model's own routing network, from the same gpkg.\n"
        f"    # This is the on-stream classifier's primary input (segment_wbody).\n"
        f'    segments_gpkg: "{{data_root}}/{{fabric}}/fabric/{fabric}.gpkg"\n'
        f"    segments_layer: nsegment\n"
        f"    # Shared CONUS inputs -- identical for every fabric, staged once per\n"
        f"    # data root (pixi run --as-is init-data-root --check confirms them).\n"
        f'    waterbody_gpkg: "{{data_root}}/input/nhd/nhd_waterbodies.gpkg"\n'
        f"    waterbody_layer: waterbodies\n"
        f'    wbd_huc12_table: "{{data_root}}/input/wbd/wbd_huc12.parquet"\n'
        f'    burn_add_waterbody_table: "{{data_root}}/input/nhd/burn_add_waterbodies.parquet"\n'
        f'    sink_points_table: "{{data_root}}/input/nhd/sink_points.parquet"\n'
        f'    ecoregions_gpkg: "{{data_root}}/input/ecoregions/us_eco_l3.gpkg"\n'
        f"    # 3DEP 1 m tile inventory + WESM project attributes (dprst_depth);\n"
        f"    # staged once by: sbatch slurm_batch/stage_dem_1m_inventory.batch\n"
        f'    dem_1m_inventory: "{{data_root}}/input/3dep/dem_1m_tile_inventory.parquet"\n'
        f'    wesm_project_attrs: "{{data_root}}/input/wesm/wesm_project_attrs.parquet"\n'
        f"    # Optional floors on the classifier counts. Leave them out unless you\n"
        f"    # know the domain has closed-basin (endorheic) lakes; set each a little\n"
        f"    # below the count the first run logs. Never add them defensively -- a\n"
        f"    # domain with no closed basin legitimately yields zero endorheic COMIDs.\n"
        f"    # min_onstream_comids: 0\n"
        f"    # min_endorheic_comids: 0\n"
    )


def add_fabric_profile(base_config_path: Path, fabric: str, logger) -> None:
    """Append a new fabric profile stub under the `fabrics:` mapping.

    Edits the file as text (not load/dump) so the extensive comments in
    base_config.yml are preserved. Idempotency is a hard error: a fabric that
    already exists is never silently overwritten.
    """
    if not re.fullmatch(r"[A-Za-z0-9_]+", fabric):
        raise ValueError(
            f"Invalid fabric name '{fabric}': use letters, digits, underscores only."
        )
    if not base_config_path.exists():
        raise FileNotFoundError(f"base_config not found: {base_config_path}")

    lines = base_config_path.read_text().splitlines(keepends=True)

    fabrics_idx = next(
        (i for i, ln in enumerate(lines) if re.match(r"^fabrics:\s*$", ln)), None
    )
    if fabrics_idx is None:
        raise ValueError(f"No top-level `fabrics:` mapping in {base_config_path}")

    if any(re.match(rf"^  {re.escape(fabric)}:\s*$", ln) for ln in lines):
        raise ValueError(
            f"Fabric '{fabric}' already exists in {base_config_path}; "
            "edit it by hand rather than re-adding."
        )

    # End of the fabrics block = first column-0 (non-indented, non-blank) line
    # after `fabrics:`, or EOF when `fabrics:` is the last top-level key.
    end = len(lines)
    for i in range(fabrics_idx + 1, len(lines)):
        ln = lines[i]
        if ln.strip() and not ln[0].isspace():
            end = i
            break

    if end > 0 and not lines[end - 1].endswith("\n"):
        lines[end - 1] += "\n"
    lines.insert(end, _fabric_profile_stub(fabric))
    base_config_path.write_text("".join(lines))
    logger.info("Added fabric profile stub '%s' to %s", fabric, base_config_path)
    logger.warning(
        "Profile '%s' has four TODO values (expected_max_hru_id, id_feature, "
        "hru_gpkg, vpu) — edit %s, then validate with "
        "scripts/check_fabric_profile.py --fabric %s.", fabric, base_config_path, fabric,
    )


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold the data_root directory layout for gfv2-params."
    )
    parser.add_argument(
        "--data_root",
        default=None,
        help="Override data_root from base_config.yml",
    )
    parser.add_argument(
        "--fabric",
        default=None,
        help="Override fabric name from base_config.yml",
    )
    parser.add_argument(
        "--base_config",
        default=None,
        help="Path to base_config.yml (default: auto-detected)",
    )
    parser.add_argument(
        "--add-fabric",
        default=None,
        metavar="NAME",
        help="Append a new fabric profile stub to base_config.yml, then scaffold its dirs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="After scaffolding, warn about missing staged input files",
    )
    args = parser.parse_args()

    logger = configure_logging("init_data_root")
    base_config_path = Path(args.base_config) if args.base_config else _DEFAULT_BASE_CONFIG

    if args.add_fabric:
        add_fabric_profile(base_config_path, args.add_fabric, logger)

    base = load_base_config(
        base_config_path,
        fabric=args.add_fabric or args.fabric,
    )

    data_root = Path(args.data_root) if args.data_root else Path(base["data_root"])
    fabric = base["fabric"]

    logger.info("data_root : %s", data_root)
    logger.info("fabric    : %s", fabric)

    init_data_root(data_root, fabric, logger)

    if args.check:
        validate_inputs(data_root, base, logger)


if __name__ == "__main__":
    main()
