"""Scaffold the data_root directory layout for gfv2-params.

Creates the expected directory tree under data_root (from base_config.yml or
--data_root) and writes a README.txt into each top-level directory explaining
its purpose and what files belong there.

Run this once before populating a new data root:
    python scripts/init_data_root.py
or for a custom root:
    python scripts/init_data_root.py --data_root /path/to/new_root --fabric myfabric

To register a brand-new fabric, append a profile stub to base_config.yml and
scaffold its directories in one step:
    python scripts/init_data_root.py --add-fabric oregon
"""

import argparse
import re
import textwrap
from pathlib import Path

from gfv2_params.config import _DEFAULT_BASE_CONFIG, load_base_config
from gfv2_params.log import configure_logging

# ---------------------------------------------------------------------------
# Directory skeleton
# Each entry is (relative_path, readme_text).  Paths ending in / are dirs;
# the readme_text is written as README.txt inside that directory.
# ---------------------------------------------------------------------------
_TREE = [
    # ---- inputs ------------------------------------------------------------
    (
        "input",
        """\
        INPUT — externally sourced data
        ================================
        All files here are provided externally and are NOT generated by this
        pipeline.  Do not delete them; they cannot be reproduced automatically.

        Subdirectory layout:
          fabric/           Per-VPU watershed fabric GeoPackages
                            (NHM_<VPU>_draft.gpkg, one per VPU)
          soils_litho/      Soils and lithology rasters/shapefiles
                            (TEXT_PRMS.tif, AWC.tif,
                             Lithology_exp_Konly_Project.*)
          lulc_veg/         Land use / land cover and vegetation rasters
                            (RootDepth.tif, CNPY.tif, Imperv.tif)
          lulc_veg/nhm_v11/ NHM v1.1 pre-derived LULC rasters
                            (LULC.tif, keep.tif, CNPY.tif)
                            (downloadable via download/nhm_v11_lulc.py)
          lulc/nlcd_annual_imperv/
                            Annual NLCD fractional imperviousness rasters
                            (downloadable via download/mrlc_impervious.py)
          lulc/nalcms_2020/ North America land cover 2020 at 30 m
                            (NA_NALCMS_landcover_2020v2_30m.tif)
                            (downloadable via download/nalcms_lulc.py)
          nhm_default/      NHM default parameter files (input to final merge)
          nhd_downloads/    Raw NHDPlus zip archives
                            (downloadable via download/rpu_rasters.py)
          depstor/          Per-fabric depression-storage inputs:
                            <fabric>_segments_wbodies.gpkg (layers nsegment, v2_wb)
                            (FDR is sourced from the shared shared/conus/vrt/fdr.vrt,
                            not staged here per-fabric.)
          twi/<rpu>/        Per-RPU topographic wetness index rasters
                            (twi.tif + .tfw/.aux.xml/.ovr/.xml sidecars).
                            Provenance: USGS ScienceBase 5f5154ba82ce4c3d12386a02
                            (https://www.sciencebase.gov/catalog/item/5f5154ba82ce4c3d12386a02 —
                            non-public link). Stage with scripts/stage_twi.sh,
                            which reads from a shared cluster mirror by default.
        """,
    ),
    ("input/fabric", None),
    ("input/soils_litho", None),
    ("input/lulc_veg", None),
    ("input/lulc_veg/nhm_v11", None),
    ("input/lulc/nlcd_annual_imperv", None),
    ("input/lulc/nalcms_2020", None),
    ("input/nhm_default", None),
    ("input/nhd_downloads", None),
    ("input/copernicus_dem", None),
    ("input/copernicus_dem/raw", None),
    ("input/depstor", None),
    ("input/twi", None),
    # ---- shared (fabric-independent intermediates) -----------------------
    (
        "shared",
        """\
        SHARED — fabric-independent pipeline intermediates
        ===================================================
        All files here are generated by this pipeline and are reused across
        every fabric. Safe to delete and rebuild (use
        scripts/build_shared_rasters.py over configs/shared_rasters/shared_rasters.yml).
        Do NOT hand-edit files here.

        Subdirectory layout:
          source/             Unzipped per-RPU NHDPlus rasters
                              (reproducible from input/nhd_downloads/ —
                               safe to delete if disk space is tight)
          per_vpu/<VPU>/      Per-VPU merged GeoTIFFs produced by the
                              shared_rasters pipeline (NEDSnapshot_merged_*.tif,
                              Hydrodem_merged_*.tif, Fdr_merged_*.tif,
                              Fac_merged_*.tif, *_slope_*.tif, *_aspect_*.tif,
                              land_mask_<vpu>.tif)
          conus/vrt/          CONUS-wide GDAL virtual rasters built by
                              build_vrt (elevation.vrt, slope.vrt,
                              aspect.vrt, fdr.vrt, twi.vrt)
          conus/derived/      Derived rasters written during parameter
                              computation (e.g. soil_moist_max.tif,
                              radtrn_<source>.tif, cnpy_resampled_<source>.tif)
          conus/borders/      Copernicus border-DEM fill (Canada/Mexico)
          conus/weights/      Polygon-to-polygon weight tables built by
                              build_weights.py (lith_weights_<fabric>.csv)
        """,
    ),
    ("shared/source", None),
    ("shared/per_vpu", None),
    ("shared/conus", None),
    ("shared/conus/vrt", None),
    ("shared/conus/derived", None),
    ("shared/conus/borders", None),
    ("shared/conus/weights", None),
]


def _fabric_tree(fabric: str) -> list:
    """Return per-fabric directory entries."""
    return [
        (
            fabric,
            f"""\
            {fabric.upper()} — fabric-scoped outputs
            {"=" * (len(fabric) + 28)}
            All outputs scoped to the '{fabric}' watershed fabric.

            Subdirectory layout:
              fabric/     Merged nhru GeoPackage produced by
                          notebooks/merge_vpu_targets.py
                          ({fabric}_nhru_merged.gpkg)
              batches/    Spatially-partitioned batch GeoPackages produced by
                          prepare_fabric.py (used by zonal stats scripts)
              depstor_rasters/
                          Per-fabric depression-storage intermediate rasters
                          produced by build_depstor_*.py
                          (imperv_binary.tif, stream_buffer.tif,
                           wbody_binary.tif, wbody_regions.tif,
                           dprst_binary.tif, onstream_binary.tif,
                           drains_to_dprst.tif)
              params/     Per-VPU and merged parameter CSVs produced by
                          create_zonal_params.py, create_soils_params.py,
                          create_ssflux_params.py, merge_params.py, and
                          merge_and_fill_params.py
              params/merged/
                          CONUS-wide merged parameter CSVs, including KNN-filled
                          ssflux parameters
            """,
        ),
        (f"{fabric}/fabric", None),
        (f"{fabric}/batches", None),
        (f"{fabric}/depstor_rasters", None),
        (f"{fabric}/params", None),
        (f"{fabric}/params/merged", None),
    ]


def init_data_root(data_root: Path, fabric: str, logger) -> None:
    tree = _TREE + _fabric_tree(fabric)

    created = []
    skipped = []

    for rel_path, readme in tree:
        d = data_root / rel_path
        if d.exists():
            skipped.append(d)
        else:
            d.mkdir(parents=True, exist_ok=True)
            created.append(d)
            logger.info("Created: %s", d)

        if readme is not None:
            readme_path = d / "README.txt"
            if not readme_path.exists():
                readme_path.write_text(textwrap.dedent(readme))

    logger.info(
        "init_data_root complete: %d created, %d already existed",
        len(created),
        len(skipped),
    )

    if skipped:
        logger.debug("Pre-existing directories (unchanged):")
        for d in skipped:
            logger.debug("  %s", d)


def validate_inputs(data_root: Path, fabric: str, logger) -> None:
    """Warn about missing staged inputs that cannot be auto-downloaded."""
    required = [
        data_root / "input" / "soils_litho" / "TEXT_PRMS.tif",
        data_root / "input" / "soils_litho" / "AWC.tif",
        data_root / "input" / "soils_litho" / "Lithology_exp_Konly_Project.shp",
        data_root / "input" / "lulc_veg" / "RootDepth.tif",
        data_root / "input" / "depstor" / f"{fabric}_segments_wbodies.gpkg",
        # Sentinel for the per-RPU TWI staging step. Run scripts/stage_twi.sh
        # if missing.
        data_root / "input" / "twi" / "01a" / "twi.tif",
    ]
    missing = [p for p in required if not p.exists()]
    if missing:
        logger.warning(
            "%d required input file(s) are not yet staged:", len(missing)
        )
        for p in missing:
            logger.warning("  MISSING: %s", p)
        logger.warning(
            "Stage these files manually before running the pipeline."
        )
    else:
        logger.info("All required staged inputs are present.")


def _fabric_profile_stub(fabric: str) -> str:
    """Return a YAML profile stub for a new fabric (2-space indented).

    Carries the three keys every fabric needs (with TODO placeholders) plus a
    commented depstor block to uncomment when that pipeline is run.
    """
    return (
        f"\n"
        f"  {fabric}:\n"
        f"    # TODO: fill these in for the '{fabric}' fabric, then drop the TODO notes.\n"
        f"    expected_max_hru_id: 0  # TODO: highest HRU id in the fabric\n"
        f"    batch_size: 10000\n"
        f"    id_feature: nat_hru_id  # TODO: HRU id column present in the fabric gpkg\n"
        f"    # Uncomment + set these only if the depstor pipeline is run for this fabric:\n"
        f'    # template_raster: "{{data_root}}/shared/conus/vrt/elevation.vrt"\n'
        f'    # fdr_raster: "{{data_root}}/shared/conus/vrt/fdr.vrt"\n'
        f'    # twi_raster: "{{data_root}}/shared/conus/vrt/twi.vrt"\n'
        f'    # segments_gpkg: "{{data_root}}/input/depstor/{{fabric}}_segments_wbodies.gpkg"\n'
        f'    # waterbody_gpkg: "{{data_root}}/input/depstor/{{fabric}}_segments_wbodies.gpkg"\n'
        f"    # waterbody_layer: v2_wb\n"
        f'    # hru_gpkg: "{{data_root}}/{{fabric}}/fabric/{{fabric}}_nhru_merged.gpkg"\n'
        f"    # hru_layer: nhru\n"
    )


def add_fabric_profile(base_config_path: Path, fabric: str, logger) -> None:
    """Append a new fabric profile stub under the `fabrics:` mapping.

    Edits the file as text (not load/dump) so the extensive comments in
    base_config.yml are preserved. Idempotency is a hard error: a fabric that
    already exists is never silently overwritten.
    """
    if not re.fullmatch(r"[A-Za-z0-9_]+", fabric):
        raise ValueError(
            f"Invalid fabric name '{fabric}': use letters, digits, underscores only."
        )
    if not base_config_path.exists():
        raise FileNotFoundError(f"base_config not found: {base_config_path}")

    lines = base_config_path.read_text().splitlines(keepends=True)

    fabrics_idx = next(
        (i for i, ln in enumerate(lines) if re.match(r"^fabrics:\s*$", ln)), None
    )
    if fabrics_idx is None:
        raise ValueError(f"No top-level `fabrics:` mapping in {base_config_path}")

    if any(re.match(rf"^  {re.escape(fabric)}:\s*$", ln) for ln in lines):
        raise ValueError(
            f"Fabric '{fabric}' already exists in {base_config_path}; "
            "edit it by hand rather than re-adding."
        )

    # End of the fabrics block = first column-0 (non-indented, non-blank) line
    # after `fabrics:`, or EOF when `fabrics:` is the last top-level key.
    end = len(lines)
    for i in range(fabrics_idx + 1, len(lines)):
        ln = lines[i]
        if ln.strip() and not ln[0].isspace():
            end = i
            break

    if end > 0 and not lines[end - 1].endswith("\n"):
        lines[end - 1] += "\n"
    lines.insert(end, _fabric_profile_stub(fabric))
    base_config_path.write_text("".join(lines))
    logger.info("Added fabric profile stub '%s' to %s", fabric, base_config_path)
    logger.warning(
        "Profile '%s' has TODO placeholders (expected_max_hru_id, id_feature) "
        "— edit %s before running the pipeline.", fabric, base_config_path,
    )


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold the data_root directory layout for gfv2-params."
    )
    parser.add_argument(
        "--data_root",
        default=None,
        help="Override data_root from base_config.yml",
    )
    parser.add_argument(
        "--fabric",
        default=None,
        help="Override fabric name from base_config.yml",
    )
    parser.add_argument(
        "--base_config",
        default=None,
        help="Path to base_config.yml (default: auto-detected)",
    )
    parser.add_argument(
        "--add-fabric",
        default=None,
        metavar="NAME",
        help="Append a new fabric profile stub to base_config.yml, then scaffold its dirs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="After scaffolding, warn about missing staged input files",
    )
    args = parser.parse_args()

    logger = configure_logging("init_data_root")
    base_config_path = Path(args.base_config) if args.base_config else _DEFAULT_BASE_CONFIG

    if args.add_fabric:
        add_fabric_profile(base_config_path, args.add_fabric, logger)

    base = load_base_config(
        base_config_path,
        fabric=args.add_fabric or args.fabric,
    )

    data_root = Path(args.data_root) if args.data_root else Path(base["data_root"])
    fabric = base["fabric"]

    logger.info("data_root : %s", data_root)
    logger.info("fabric    : %s", fabric)

    init_data_root(data_root, fabric, logger)

    if args.check:
        validate_inputs(data_root, fabric, logger)


if __name__ == "__main__":
    main()
