"""Scaffold the data_root directory layout for gfv2-params.

Creates the expected directory tree under data_root (from base_config.yml or
--data_root) and writes a README.txt into each top-level directory explaining
its purpose and what files belong there.

Run this once before populating a new data root:
    python scripts/init_data_root.py
or for a custom root:
    python scripts/init_data_root.py --data_root /path/to/new_root --fabric myfabric
"""

import argparse
import textwrap
from pathlib import Path

from gfv2_params.config import load_base_config
from gfv2_params.log import configure_logging

# ---------------------------------------------------------------------------
# Directory skeleton
# Each entry is (relative_path, readme_text).  Paths ending in / are dirs;
# the readme_text is written as README.txt inside that directory.
# ---------------------------------------------------------------------------
_TREE = [
    # ---- inputs ------------------------------------------------------------
    (
        "input",
        """\
        INPUT — externally sourced data
        ================================
        All files here are provided externally and are NOT generated by this
        pipeline.  Do not delete them; they cannot be reproduced automatically.

        Subdirectory layout:
          fabric/           Per-VPU watershed fabric GeoPackages
                            (NHM_<VPU>_draft.gpkg, one per VPU)
          soils_litho/      Soils and lithology rasters/shapefiles
                            (TEXT_PRMS.tif, AWC.tif,
                             Lithology_exp_Konly_Project.*)
          lulc_veg/         Land use / land cover and vegetation rasters
                            (RootDepth.tif, CNPY.tif, Imperv.tif)
          lulc_veg/nhm_v11/ NHM v1.1 pre-derived LULC rasters
                            (LULC.tif, keep.tif, CNPY.tif)
                            (downloadable via download/nhm_v11_lulc.py)
          lulc/nlcd_annual_imperv/
                            Annual NLCD fractional imperviousness rasters
                            (downloadable via download/mrlc_impervious.py)
          lulc/nalcms_2020/ North America land cover 2020 at 30 m
                            (NA_NALCMS_landcover_2020v2_30m.tif)
                            (downloadable via download/nalcms_lulc.py)
          nhm_default/      NHM default parameter files (input to final merge)
          nhd_downloads/    Raw NHDPlus zip archives
                            (downloadable via download/rpu_rasters.py)
        """,
    ),
    ("input/fabric", None),
    ("input/soils_litho", None),
    ("input/lulc_veg", None),
    ("input/lulc_veg/nhm_v11", None),
    ("input/lulc/nlcd_annual_imperv", None),
    ("input/lulc/nalcms_2020", None),
    ("input/nhm_default", None),
    ("input/nhd_downloads", None),
    # ---- work (intermediates) ----------------------------------------------
    (
        "work",
        """\
        WORK — reproducible pipeline intermediates
        ===========================================
        All files here are generated by this pipeline and can be safely deleted
        and rebuilt.  Do NOT hand-edit files here.

        Subdirectory layout:
          nhd_extracted/      Unzipped per-RPU NHDPlus rasters
                              (reproducible from input/nhd/downloads/ —
                               safe to delete if disk space is tight)
          nhd_merged/<VPU>/   Per-VPU merged GeoTIFFs produced by
                              merge_rpu_by_vpu.py and compute_slope_aspect.py
                              (NEDSnapshot_merged_*.tif, Hydrodem_merged_*.tif,
                               Fdr_merged_*.tif, Fac_merged_*.tif,
                               NEDSnapshot_merged_slope_*.tif,
                               NEDSnapshot_merged_aspect_*.tif)
          nhd_merged/*.vrt    CONUS-wide GDAL virtual rasters built by
                              build_vrt.py (elevation.vrt, slope.vrt,
                              aspect.vrt)
          derived_rasters/    Derived rasters written during parameter
                              computation (e.g. soil_moist_max.tif)
          weights/            Polygon-to-polygon weight tables built by
                              build_weights.py (lith_weights_<fabric>.csv)
        """,
    ),
    ("work/nhd_extracted", None),
    ("work/nhd_merged", None),
    ("work/derived_rasters", None),
    ("work/weights", None),
]


def _fabric_tree(fabric: str) -> list:
    """Return per-fabric directory entries."""
    return [
        (
            fabric,
            f"""\
            {fabric.upper()} — fabric-scoped outputs
            {"=" * (len(fabric) + 28)}
            All outputs scoped to the '{fabric}' watershed fabric.

            Subdirectory layout:
              fabric/     Merged nhru GeoPackage produced by
                          notebooks/merge_vpu_targets.py
                          ({fabric}_nhru_merged.gpkg)
              batches/    Spatially-partitioned batch GeoPackages produced by
                          prepare_fabric.py (used by zonal stats scripts)
              params/     Per-VPU and merged parameter CSVs produced by
                          create_zonal_params.py, create_soils_params.py,
                          create_ssflux_params.py, merge_params.py, and
                          merge_and_fill_params.py
              params/merged/
                          CONUS-wide merged parameter CSVs, including KNN-filled
                          ssflux parameters
            """,
        ),
        (f"{fabric}/fabric", None),
        (f"{fabric}/batches", None),
        (f"{fabric}/params", None),
        (f"{fabric}/params/merged", None),
    ]


def init_data_root(data_root: Path, fabric: str, logger) -> None:
    tree = _TREE + _fabric_tree(fabric)

    created = []
    skipped = []

    for rel_path, readme in tree:
        d = data_root / rel_path
        if d.exists():
            skipped.append(d)
        else:
            d.mkdir(parents=True, exist_ok=True)
            created.append(d)
            logger.info("Created: %s", d)

        if readme is not None:
            readme_path = d / "README.txt"
            if not readme_path.exists():
                readme_path.write_text(textwrap.dedent(readme))

    logger.info(
        "init_data_root complete: %d created, %d already existed",
        len(created),
        len(skipped),
    )

    if skipped:
        logger.debug("Pre-existing directories (unchanged):")
        for d in skipped:
            logger.debug("  %s", d)


def validate_inputs(data_root: Path, fabric: str, logger) -> None:
    """Warn about missing staged inputs that cannot be auto-downloaded."""
    required = [
        data_root / "input" / "soils_litho" / "TEXT_PRMS.tif",
        data_root / "input" / "soils_litho" / "AWC.tif",
        data_root / "input" / "soils_litho" / "Lithology_exp_Konly_Project.shp",
        data_root / "input" / "lulc_veg" / "RootDepth.tif",
    ]
    missing = [p for p in required if not p.exists()]
    if missing:
        logger.warning(
            "%d required input file(s) are not yet staged:", len(missing)
        )
        for p in missing:
            logger.warning("  MISSING: %s", p)
        logger.warning(
            "Stage these files manually before running the pipeline."
        )
    else:
        logger.info("All required staged inputs are present.")


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold the data_root directory layout for gfv2-params."
    )
    parser.add_argument(
        "--data_root",
        default=None,
        help="Override data_root from base_config.yml",
    )
    parser.add_argument(
        "--fabric",
        default=None,
        help="Override fabric name from base_config.yml",
    )
    parser.add_argument(
        "--base_config",
        default=None,
        help="Path to base_config.yml (default: auto-detected)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="After scaffolding, warn about missing staged input files",
    )
    args = parser.parse_args()

    logger = configure_logging("init_data_root")
    base = load_base_config(Path(args.base_config) if args.base_config else None)

    data_root = Path(args.data_root) if args.data_root else Path(base["data_root"])
    fabric = args.fabric if args.fabric else base["fabric"]

    logger.info("data_root : %s", data_root)
    logger.info("fabric    : %s", fabric)

    init_data_root(data_root, fabric, logger)

    if args.check:
        validate_inputs(data_root, fabric, logger)


if __name__ == "__main__":
    main()
